### ISSUE TITLE
Feature Request: UpmGitExtension Support

### ISSUE THREAD

**Issue by crazyjackel** [MechWarrior99/Bewildered-Core#4]
UPM Git Extension is a popular Package Manager Extension that allows the conduct of versioning and updates based on the releases on a GitHub Page. I am submitting an issue to request support for this.

Why Support:
- Whenever you update a package to fix errors or improve feature sets, it is important that you allow them to update. Currently in Unity, when you install a package, it locks to a certain version at a time. If I want the recent fix: [fed7238](https://github.com/MechWarrior99/Bewildered-Core/commit/fed723890e7f04e6d4dd01dedf32fb8ef351e3ba) for my project, I have to uninstall and reinstall. Also, I am not able to target specific versions, in case a future version breaks something, I would very much like to target previous versions as my package and not have my project break if I load it from a different computer. For this UPM Git Extension (https://github.com/mob-sakai/UpmGitExtension#usage) is a popular Package Manager Extension to solve these problems.

How to Support: 
- Whenever a new version comes out, update the package.json to match the release number. Then create a new release with a tag that matches the version number.

Example:
https://github.com/crazyjackel/redmoon-reactiveKit

In this package of my own creation, when I update the package.json version, I also draft a release. As you can see, I have a release with a tag that matches my version number. Anyone can produce dependency on my older versions (though many of them are quite broken). It is also a one button update.

**Comment by crazyjackel** [comment]
Note, the Update Feature is for older versions of Unity, newer versions allow for one button update for Git Packages, but not for versioning.

**Comment by MechWarrior99** [comment]
Noted! Will do for future updates.
